### ISSUE TITLE
Type (VaccineType is Primo Vaccin or Rappel) : must be series from ProtocolApplied in place of reason code?

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/vaccination#19] opened 2021-12-03 08:50 UTC
Type (the VaccineType is Primo Vaccin or Rappel) : must be series from ProtocolApplied in place of reason code ?

**Comment by costateixeira** [comment] 2022-01-05 17:24
Should not be reasonCode. Should be protocolApplied

**Comment by bdc-ehealth** [comment] 2022-04-22 14:45
duplicate of #12

**Closed by bdc-ehealth** 2022-04-22 14:45 UTC
Labels: need-input
